name: iprocrastinate
description: A productivity web app to help overcome procrastination.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  web: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.7
  build_web_compilers: ^4.0.7
  lints: ^3.0.0
  test: ^1.24.0